import React, { useState, useEffect } from 'react';
import { getCatalog, saveCatalogItem, deleteCatalogItem } from '../services/dataService';
import { CatalogItem } from '../types';
import { Search, Plus, Trash2, Edit2, Save, X, DollarSign, Tag, Loader2 } from 'lucide-react';
import { formatCurrency } from '../constants';

const PriceTable: React.FC = () => {
    const [items, setItems] = useState<CatalogItem[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [editingItem, setEditingItem] = useState<CatalogItem | null>(null);
    const [isModalOpen, setIsModalOpen] = useState(false);

    useEffect(() => {
        loadCatalog();
    }, []);

    const loadCatalog = async () => {
        setIsLoading(true);
        const data = await getCatalog();
        setItems(data || []);
        setIsLoading(false);
    };

    const handleEdit = (item: CatalogItem) => {
        setEditingItem({ ...item });
        setIsModalOpen(true);
    };

    const handleAddNew = () => {
        setEditingItem({
            id: '', // Will be generated by DB or service
            name: '',
            category: 'Produção',
            lastPrice: 0,
            usageCount: 0
        });
        setIsModalOpen(true);
    };

    const handleDelete = async (id: string) => {
        if (confirm('Tem certeza que deseja diminuir a importância deste item? (Ele só será excluído se não tiver uso)')) {
            // In a real scenario we might soft delete or actually delete
            await deleteCatalogItem(id);
            loadCatalog();
        }
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!editingItem || !editingItem.name) return;

        try {
            await saveCatalogItem(editingItem);
            setIsModalOpen(false);
            setEditingItem(null);
            loadCatalog();
        } catch (error) {
            console.error(error);
            alert('Erro ao salvar item.');
        }
    };

    const filteredItems = items.filter(i =>
        i.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        i.category.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="p-8 max-w-[1600px] mx-auto min-h-screen bg-slate-50">
            <div className="flex justify-between items-center mb-8">
                <div>
                    <h1 className="text-3xl font-extrabold text-slate-900 mb-2">Tabela de Preços Global</h1>
                    <p className="text-slate-500 font-medium">Gerencie os itens e valores sugeridos aprendidos pelo sistema.</p>
                </div>
                <button
                    onClick={handleAddNew}
                    className="bg-amber-600 hover:bg-amber-700 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 shadow-lg hover:shadow-xl transition-all hover:scale-105 active:scale-95"
                >
                    <Plus size={20} /> Adicionar Novo Item manually
                </button>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 mb-8">
                <div className="relative">
                    <Search className="absolute left-4 top-4 text-slate-400" size={20} />
                    <input
                        className="w-full pl-12 pr-4 py-3.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500 outline-none text-slate-700 font-medium transition-all"
                        placeholder="Buscar por nome do serviço ou categoria..."
                        value={searchTerm}
                        onChange={e => setSearchTerm(e.target.value)}
                    />
                </div>
            </div>

            {isLoading ? (
                <div className="flex flex-col items-center justify-center py-20 text-slate-400 gap-3">
                    <Loader2 size={40} className="animate-spin text-amber-600" />
                    <p>Carregando tabela de preços...</p>
                </div>
            ) : (
                <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left">
                            <thead>
                                <tr className="bg-slate-50 border-b border-slate-200">
                                    <th className="p-5 font-bold text-slate-600 text-sm uppercase tracking-wider">Serviço / Item</th>
                                    <th className="p-5 font-bold text-slate-600 text-sm uppercase tracking-wider">Categoria</th>
                                    <th className="p-5 font-bold text-slate-600 text-sm uppercase tracking-wider text-right">Valor Sugerido</th>
                                    <th className="p-5 font-bold text-slate-600 text-sm uppercase tracking-wider text-center">Uso</th>
                                    <th className="p-5 font-bold text-slate-600 text-sm uppercase tracking-wider text-right">Ações</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100">
                                {filteredItems.map(item => (
                                    <tr key={item.id} className="hover:bg-amber-50/30 transition-colors group">
                                        <td className="p-5 font-bold text-slate-800">{item.name}</td>
                                        <td className="p-5">
                                            <span className="bg-slate-100 text-slate-600 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide border border-slate-200">
                                                {item.category}
                                            </span>
                                        </td>
                                        <td className="p-5 text-right font-mono font-bold text-slate-700">
                                            {formatCurrency(item.lastPrice)}
                                        </td>
                                        <td className="p-5 text-center">
                                            <span className="text-xs font-bold bg-amber-100 text-amber-800 px-2 py-1 rounded-md">
                                                {item.usageCount}x
                                            </span>
                                        </td>
                                        <td className="p-5 text-right">
                                            <div className="flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <button
                                                    onClick={() => handleEdit(item)}
                                                    className="p-2 bg-white border border-slate-200 rounded-lg text-slate-500 hover:text-amber-600 hover:border-amber-600 transition-all shadow-sm"
                                                    title="Editar"
                                                >
                                                    <Edit2 size={16} />
                                                </button>
                                                <button
                                                    onClick={() => handleDelete(item.id)}
                                                    className="p-2 bg-white border border-slate-200 rounded-lg text-slate-500 hover:text-red-600 hover:border-red-600 transition-all shadow-sm"
                                                    title="Excluir"
                                                >
                                                    <Trash2 size={16} />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                    {filteredItems.length === 0 && (
                        <div className="p-10 text-center text-slate-500">
                            Nenhum item encontrado. Adicione novos itens ou crie orçamentos para alimentar a tabela.
                        </div>
                    )}
                </div>
            )}

            {/* Modal */}
            {isModalOpen && editingItem && (
                <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden">
                        <div className="bg-slate-900 p-6 flex justify-between items-center">
                            <h3 className="text-xl font-bold text-white flex items-center gap-2">
                                {editingItem.id ? <Edit2 size={20} /> : <Plus size={20} />}
                                {editingItem.id ? 'Editar Item' : 'Novo Item'}
                            </h3>
                            <button
                                onClick={() => setIsModalOpen(false)}
                                className="text-slate-400 hover:text-white transition-colors"
                            >
                                <X size={24} />
                            </button>
                        </div>

                        <form onSubmit={handleSave} className="p-8 space-y-6">
                            <div>
                                <label className="block text-sm font-bold text-slate-700 mb-2">Nome do Serviço / Item</label>
                                <input
                                    autoFocus
                                    required
                                    type="text"
                                    className="w-full px-4 py-3 rounded-xl border border-slate-300 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 outline-none transition-all font-medium"
                                    value={editingItem.name}
                                    onChange={e => setEditingItem({ ...editingItem, name: e.target.value })}
                                    placeholder="Ex: Diária de Operador de Câmera"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 mb-2">Categoria</label>
                                    <div className="relative">
                                        <Tag className="absolute left-3 top-3.5 text-slate-400" size={18} />
                                        <select
                                            className="w-full pl-10 pr-4 py-3 rounded-xl border border-slate-300 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 outline-none transition-all appearance-none bg-white"
                                            value={editingItem.category}
                                            onChange={e => setEditingItem({ ...editingItem, category: e.target.value })}
                                        >
                                            <option value="Produção">Produção</option>
                                            <option value="Equipamentos">Equipamentos</option>
                                            <option value="Logística">Logística</option>
                                            <option value="Outros">Outros</option>
                                        </select>
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-sm font-bold text-slate-700 mb-2">Valor Sugerido (R$)</label>
                                    <div className="relative">
                                        <DollarSign className="absolute left-3 top-3.5 text-slate-400" size={18} />
                                        <input
                                            type="text"
                                            className="w-full pl-10 pr-4 py-3 rounded-xl border border-slate-300 focus:ring-2 focus:ring-amber-500 focus:border-amber-500 outline-none transition-all font-mono font-bold text-slate-700"
                                            value={editingItem.lastPrice ? editingItem.lastPrice.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) : ''}
                                            onChange={e => {
                                                const val = Number(e.target.value.replace(/\D/g, '')) / 100;
                                                setEditingItem({ ...editingItem, lastPrice: val });
                                            }}
                                            placeholder="0,00"
                                        />
                                    </div>
                                </div>
                            </div>

                            <div className="pt-4 flex gap-3 justify-end">
                                <button
                                    type="button"
                                    onClick={() => setIsModalOpen(false)}
                                    className="px-6 py-3 rounded-xl bg-slate-100 text-slate-600 font-bold hover:bg-slate-200 transition-colors"
                                >
                                    Cancelar
                                </button>
                                <button
                                    type="submit"
                                    className="px-8 py-3 rounded-xl bg-amber-600 text-white font-bold hover:bg-amber-700 shadow-lg shadow-amber-600/20 transition-all active:scale-95 flex items-center gap-2"
                                >
                                    <Save size={18} /> Salvar Item
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};

export default PriceTable;
